# Generated by Django 5.1.15 on 2026-07-11 12:37

import apps.services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("escalation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "integration_key",
                    models.CharField(
                        default=apps.services.models.generate_integration_key,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("runbook_url", models.URLField(blank=True, null=True)),
                ("runbook_markdown", models.TextField(blank=True, null=True)),
                (
                    "escalation_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="escalation.escalationpolicy",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
