# Generated by Django 5.1.15 on 2026-07-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('alertmanager', 'Alertmanager'), ('datadog', 'Datadog'), ('cloudwatch', 'CloudWatch'), ('sentry', 'Sentry'), ('generic', 'Generic')], max_length=16)),
                ('external_id', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=16)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved')], max_length=16)),
                ('received_at', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='services.service')),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('service', 'source', 'external_id'), name='uniq_alert_dedup_key')],
            },
        ),
    ]
