# Generated by Django 5.1.15 on 2026-07-11 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='triggered', max_length=16)),
                ('current_escalation_step', models.PositiveIntegerField(default=0)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='services.service')),
                ('triggering_alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('alert_received', 'Alert received'), ('notification_sent', 'Notification sent'), ('escalated', 'Escalated'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('note_added', 'Note added')], max_length=32)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
