# Generated by Django 5.1.15 on 2026-07-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("repeat_count", models.PositiveIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_policies",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscalationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule"),
                            ("user", "User"),
                            ("team", "Team"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                ("timeout_minutes", models.PositiveIntegerField()),
                ("notify_channels", models.JSONField(default=list)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="escalation.escalationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("policy", "order")},
            },
        ),
    ]
